// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSBMboL1Lyaqne_jkSKd-QCvGH_o4Rto',
    appId: '1:426376798827:web:496766c9db5db82e0f472e',
    messagingSenderId: '426376798827',
    projectId: 'altyn-arzuw',
    authDomain: 'altyn-arzuw.firebaseapp.com',
    storageBucket: 'altyn-arzuw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWbCn5a_ZbWkA7AJK7GJgkYrzWKA86Muk',
    appId: '1:426376798827:android:7d6a41b18cf537550f472e',
    messagingSenderId: '426376798827',
    projectId: 'altyn-arzuw',
    storageBucket: 'altyn-arzuw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQaYphyBRWtDfiEtOzXinCkgsdmqddVI',
    appId: '1:426376798827:ios:d21f627cda3a382d0f472e',
    messagingSenderId: '426376798827',
    projectId: 'altyn-arzuw',
    storageBucket: 'altyn-arzuw.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );
}
